### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by lsx2003** [lsx2003/Github-Prcatice#1]
## 주요 기능
todo Create 

### 해당 기능을 구현하기 위한 작업
1. [x]  컴포넌트 작성
2. [x] server에 데이터 요청
3. [x] 받아온 데이터 상태 관리
4. [x] 데이터 컴포넌트에 적용 및 렌더링 테스트

### 예상 작업 시간 : 3h

**Comment by lsx2003** [comment]
complete
